DynamicPlannerROS:
   yaw_goal_tolerance: 0.1 # about 6 degrees
   xy_goal_tolerance: 0.05  # 5 cm
   pdist_scale: 0.4
   gdist_scale: 0.8
   occdist_scale: 0.05

   ang_for_left: 45.0
   ang_for_right: 45.0
   obs_detect_dist: 1.0
   follow_vel: 1.0
   vis_ang_for_left: 10.0
   vis_ang_for_right: 10.0
