# Move base configure settings

shutdown_costmap: false

controller_frequency: 20.0
controller_patience: 3.0

planner_frequency: 0.0
planner_patience: 5.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

local_costmap/inscribed_radius: 0.5
local_costmap/circumscribed_radius: 0.8

# base_local_planner: base_local_planner/TrajectoryPlannerROS
base_local_planner: base_local_planner/DynamicPlannerROS
base_global_planner: static_planner/StaticPlanner
